# -*- coding: utf-8 -*-
"""👑 AI Resume Generator (Python + FPDF).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7EQrdWvfIHGcwnZPyFBlHwAo9nTHWlu
"""

!pip install fpdf
from fpdf import FPDF

# Define custom A4 PDF class
class ResumePDF(FPDF):
    def header(self):
        # Use a Unicode font like "DejaVuSans" or "ArialUnicodeMS" if available,
        # otherwise stick to basic fonts and avoid non-ASCII characters.
        # For demonstration, we will use a basic font and remove the emoji.
        self.set_font("Arial", "B", 14)
        self.set_text_color(0, 102, 204)
        # Removed the emoji 🔹 as it causes encoding issues
        self.cell(0, 10, f"{name.upper()}", ln=True, align='C')
        self.set_font("Arial", "", 10)
        self.set_text_color(0, 0, 0)
        contact_info = f"📞 {phone} | ✉️ {email} | {linkedin} | {github}" # Keeping some common symbols, might need adjustment
        self.cell(0, 8, contact_info, ln=True, align='C')
        self.ln(5)
        self.line(10, 30, 200, 30)

    def section(self, title, content):
        self.set_font("Arial", "B", 12)
        self.set_text_color(0, 0, 128)
        self.cell(0, 10, title, ln=True)
        self.set_text_color(0, 0, 0)
        self.set_font("Arial", "", 11)
        # Ensure content is treated as UTF-8
        self.multi_cell(0, 8, content.encode('latin-1', 'replace').decode('latin-1')) # Simple workaround, full unicode requires font embedding
        self.ln(3)

# 🔹 Collect input from user
print("👑 Enter your resume details below:\n")

name = input("Full Name: ")
phone = input("Phone Number: ")
email = input("Email: ")
linkedin = input("LinkedIn Profile URL: ")
github = input("GitHub Profile URL: ")

profile_summary = input("\nProfile Summary:\n")

technical_skills = input("\nTechnical Skills (use commas or newlines):\n")

projects = input("\nProjects (use • bullets or numbered list):\n")

education = input("\nEducation Details:\n")

certifications = input("\nCertifications & Courses:\n")

interests = input("\nPersonal Interests:\n")

#  Generate Resume PDF
pdf = ResumePDF()
pdf.add_page()

pdf.section("PROFILE SUMMARY", profile_summary)
pdf.section("TECHNICAL SKILLS", technical_skills)
pdf.section("PROJECTS", projects)
pdf.section("EDUCATION", education)
pdf.section("CERTIFICATIONS & COURSES", certifications)
pdf.section("PERSONAL INTERESTS", interests)

filename = "Generated_Resume.pdf"
pdf.output(filename)

print(f"\n✅ Done! Your resume is saved as: {filename}")

